website/auth.py
import logging

from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import re
from flask_bcrypt import Bcrypt

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()

        if user:
            if Bcrypt().check_password_hash(user.password, password.encode('utf-8')):
                login_user(user, remember=True)
                flash('logged in successfully!', category='success')
                # Password read once: Password = None
                password = None
                return redirect(url_for('views.profile'))
            else:
                flash('incorrect password, try again.', category='error')
                logging.error(f"Incorrect password from user: {username} IP: {request.remote_addr}")
        else:
            flash('username does not exist.', category='error')
            logging.error(f"Username does not exist: {username} IP: {request.remote_addr}")
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('logged out successfully!', category='success')
    return redirect(url_for('views.index'))


@auth.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        user = User.query.filter_by(username=username).first()

        if validate_user(username, password, repassword, user) == True:
            new_user = User(username=username, password=Bcrypt().generate_password_hash(password).decode('utf-8'))
            db.session.add(new_user)
            db.session.commit()
            # read once passwords
            password = None
            repassword = None
            flash('account created', category='success')
            return redirect(url_for('views.profile'))
        elif validate_user(username, password, repassword, user) != True:
            flash(validate_user(username, password, repassword, user), category='error')
    return render_template("create.html", user=current_user)


def validate_user(username, password, repassword, user):
    # regex: contain 1 Upper, 1 lower, 1 number, 1 special character, 8 characters
    pattern = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"

    if user:
        return "Username already exists."
    elif len(username) < 5:
        return "Username must be at least 5 characters."
    elif password != repassword:
        return "Passwords don't match."
    elif not re.match(pattern, password):
        return "Password must contain 1 Upper, 1 lower, 1 number, 1 special character, 8 characters"
    else:
        return True

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, render_template_string
from flask_login import login_required, current_user
from .models import Img, Comment, Share, User, Entry
from . import db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER
import os
import logging
from werkzeug.utils import secure_filename


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html', user=current_user)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template('profile.html', user=current_user, )


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    if request.method == 'POST':
        file = request.files['file']
        if not file:
            flash('No Picture uploaded', category='error')
        picCount = Img.query.filter_by(user_id=current_user.id).count()

        #insecure filename
        filename = file.filename

        #Secure filename
        #filename = secure_filename(file.filename)

        # Users can't upload more than 100 images
        if picCount >= 99:
            logging.error(f"User: {current_user.username} IP: {request.remote_addr} has reached the max number of images")
            return 'Upload limit reached!', 400

        if not filename: #or not allowed_file(filename):
            logging.error(f"User: {current_user.username} IP: {request.remote_addr} tried to upload a file with an invalid extension")
            return 'Bad upload!', 400

        image = Img(filename=filename, user_id=current_user.id)
        db.session.add(image)
        db.session.commit()
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        flash('Picture uploaded : %s' % filename, category='Success')
    return render_template("upload.html", user=current_user)


@views.route('/showimage/<id>/', methods=['GET'])
@login_required
def show_image(id):
    usr = User.query.all()
    img = Img.query.filter_by(id=id).first()
    if not img:
        #return 'Img Not Found: ' + id, 404
        #vulnerable to SSTI
        return render_template_string('Img Not Found: ' + id), 404
    return render_template("image.html", usernames=usr, user=current_user, img=img, owner=img.user_id == current_user.id)


@views.route('/add_comment', methods=['POST'])
@login_required
def add_comment():
    if request.method == 'POST':
        image_id = request.form['imageid']
        comment = request.form['text']

        commentCount = Comment.query.filter_by(image_id=image_id).count()

        # Images can't have more than 100 comments
        if commentCount >= 99:
            return 'Comment limit reached!', 400

        new_comment = Comment(data=comment, user_id=current_user.id, image_id=image_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment added!', category='success')

        return redirect(url_for('views.show_image', id=image_id))


@views.route('/shareimage', methods=['POST'])
@login_required
def share_image():
    if request.method == 'POST':
        to_user = request.form.get('userid')
        imgId = request.form.get('imgId')
        shared_filename = db.session.query(Img.filename).filter(Img.id == imgId)
        new_share = Share(image_id=imgId, from_user=current_user.id, to_user=to_user, filename=shared_filename)
        db.session.add(new_share)
        db.session.commit()
        flash('Image has been shared!', category='success')
        return redirect(url_for('views.profile'))


@views.route('/unshare', methods=['POST'])
@login_required
def unshare():
    if request.method == 'POST':
        shared_id = request.form['shareduser']
        image_id = request.form['imageid']

        Share.query.filter(Share.to_user == shared_id and Share.image_id == image_id).delete()
        flash('Image unshared',)
        return redirect(url_for('views.profile'))
    else:
        return redirect(url_for('views.no_way'))


@views.route('/no_way', methods=['GET'])
def no_way():
    return render_template('no_way.html')


@views.route('/show_entries', methods=['GET'])
def show_entries():
    entries = Entry.query.all()
    return render_template('show_entries.html', user=current_user, entries=entries)


@views.route('/add', methods=['POST']) #add entries
@login_required
def add_entry():
    if request.method == 'POST':
        text = request.form['text']
        title = request.form['title']
        new_entry = Entry(title=title, text=text)
        db.session.add(new_entry)
        db.session.commit()
        flash('New entry was successfully posted')
    return redirect(url_for('views.show_entries'))

website/templates/create.html
{% extends "layout.html" %}
{% block body %}
  <h2>Create</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('auth.create') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
        <dt>Retype password:
      <dd><input type=password name=repassword>
      <dd><input type=submit value=Create>
    </dl>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  </form>
{% endblock %}

website/templates/image.html
{% extends "layout.html" %}
{% block body %}

        <a href="{{ url_for('views.profile') }}">Back</a>

        <ul class=entries>
            <h2>{{ img.filename }}</h2>
            <img class="img-center" src={{ url_for('static', filename = 'img/user_uploads/%s' % (img.filename)) }} width="400">

            {% if owner %}
                <h2>Share Image</h2>

         <form action="{{ url_for('views.share_image') }}" method=post>
             Share with:
             <select class="share-select-center" name="userid">
                 {% for user in usernames %}
                     <option value="{{ user.id }}">{{ user.username }}</option>
                 {% endfor %}
             </select>
             <input name="imgId" type="hidden" value="{{ img.id }}">
             <input class="share-input-right" type=submit value=Share>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
         </form>

                <form action="{{ url_for('views.unshare') }}" method="post">
                    Unshare:
                    <select class="share-select-center" name="shareduser">
                        {% for s in shares %}
                            <option value="{{ s.id }}">{{ s.username }}</option>
                        {% endfor %}
                    </select>
                    <input name="imageid" type="hidden" value="{{ img.id }}">
                    <input class="share-input-right" type="submit" value="Unshare">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                </form>

            {% endif %}

            <li><h2>Comments</h2>
                <form action="{{ url_for('views.add_comment') }}" method=post class=add-entry>
                    <dl>
                        <input name="imageid" type="hidden" value="{{ img.id }}">
                        <dt>Text:
                        <dd><textarea name=text rows=5 cols=40></textarea>
                        <dd><input type=submit value=Comment>
                    </dl>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                </form>
                {% for msg in img.comments %}
                    <li><h3>{{ msg.user_id }}</h3>{{ msg.data }}
                        {% else %}
                    <li><em>Unbelievable. No comments so far</em>
                {% endfor %}
        </ul>

{% endblock %}

website/templates/index.html
{% extends "layout.html" %}
{% block body %}
<label class="label-top">
    Welcome to Image-2-Image!!
  </label>
    <br/>
    <label class="label-italic">
    login or create a profile, to start sharing your images!!
    </label>
    <image class="img-center" src="{{ url_for('static', filename = 'img/wizard.jpg') }}" width="400" height="500"/>
{% endblock %}

website/templates/layout.html
<!doctype html>
<title>Image-2-Image</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>
  <h1>Image-2-Image</h1>
  {% if user.is_authenticated %}
<h2>User: {{ user.username }}</h2>
  {% endif %}
  <div class=metanav>
  {% if not user.is_authenticated %}
    <a href="{{ url_for('auth.login') }}">log in</a>
    <a href="{{ url_for('auth.create') }}">Sign-up</a>
  {% else %}
      <a href="{{ url_for('views.profile') }}">profile</a>
    <a href="{{ url_for('auth.logout') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

website/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('auth.login') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  </form>
{% endblock %}

website/templates/no_way.html
{% extends "layout.html" %}
{% block body %}
    <div>
        <image src="{{ url_for('static', filename = 'img/SayTheMagicWord.gif') }}" width="100%"/>
    </div>
{% endblock %}

website/templates/profile.html
{% extends "layout.html" %}
{% block body %}

        <a href="{{ url_for('views.upload') }}">Upload image</a>


        <ul class=entries>

            <li><h2>Your images</h2>
                {%  for img in user.images %}
                    <h3> {{ img.name }} </h3>
                    <a href="{{ url_for('views.show_image', id=img.id) }}">
                     <img src={{ url_for('static', filename = 'img/user_uploads/%s' % (img.filename)) }} width="200">
                    </a>
                {% else %}
                    <li>Unbelievable. No images so far</li>
                {% endfor %}


            <li><h2>Images shared with you</h2>
                 {%  for shared in user.shares %}
                  <h3> {{ shared.name }} </h3>
                    <a href="{{ url_for('views.show_image', id=shared.image_id) }}">
                     <img src={{ url_for('static', filename = 'img/%s' % (shared.filename)) }} width="500">>
                     </a>
                {% else %}
                    <li>Unbelievable. No images so far</li>

                {% endfor %}

        </ul>

{% endblock %}

website/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
  {% if user.is_authenticated %}
    <form action="{{ url_for('views.add_entry') }}" method=post class=add-entry>
      <dl>
        <dt>Title:
        <dd><input type=text size=30 name=title>
        <dt>Text:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dd><input type=submit value=Share>
      </dl>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    </form>
  {% endif %}
  <ul class=entries>
  {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
{% endblock %}

website/templates/upload.html
{% extends "layout.html" %}
{% block body %}

        <a href="{{ url_for('views.profile') }}">Back</a>
        <ul class=entries>

            <li><h2>Upload image</h2>

                <form action="" method=post enctype=multipart/form-data>
                    <p><input type=file name=file>
                        <input type=submit value=Upload>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                </form>


        </ul>


{% endblock %}